stages:
  - build
  - quality
  - test
  - security
  - docker
  - deploy

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml

Build:
  image: node:latest
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    name: "MPG-CALCULATOR-BUILD-${CI_COMMIT_REF_SLUG}"
    paths:
      - ./dist
    expire_in: 1 day

Test:
  image: node:latest
  stage: test
  script:
    - npm install --progress=false
    - npm run test:cover
  artifacts:
    paths:
    - coverage/lcov-report
  except:
    - tags

code_quality:
  stage: quality
  except:
    - tags

sast:
  stage: security
  except:
    - tags

dependency_scanning:
  stage: security
  only:
    refs:
      - master
    changes:
      - package*.json

license_scanning:
  stage: security
  coverage: '/Do not get coverage: \d+\.\d+/'
  except:
    - tags

.docker:
  image: docker:18.09.7
  stage: docker
  cache: {}
  dependencies: []
  services:
    - docker:18.09.7-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER registry.gitlab.com --password-stdin
    - docker pull registry.gitlab.com/mpg-calculator:master || true
  allow_failure: true
  timeout: 15m

Review Image:
  extends: .docker
  variables:
    IMAGE_TAG: "$CI_COMMIT_REF_SLUG"
  script:
    - docker build --cache-from registry.gitlab.com/mpg-calculator:master -t registry.gitlab.com/mpg-calculator:$IMAGE_TAG .
    - docker push registry.gitlab.com/mpg-calculator:$IMAGE_TAG
  except:
    - tags

Stable Image:
  extends: .docker
  variables:
    IMAGE_TAG: "$CI_COMMIT_REF_NAME"
  script:
    - docker build --cache-from registry.gitlab.com/mpg-calculator:master -t registry.gitlab.com/mpg-calculator:latest -t registry.gitlab.com/mpg-calculator:$IMAGE_TAG .
    - docker push registry.gitlab.com/mpg-calculator:$IMAGE_TAG
  only:
    - tags

pages: # the job must be named pages
  image: node:latest
  stage: deploy
  dependencies:
    - Build
  script:
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \; # active gzip
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  environment:
    name: production
    url: https://muybien.gitlab.io/mpg-calculator
  only:
    - tags
