# Global Configuration
stages:
  - prepare
  - build
  - quality
  - test
  - deploy

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - when: always

default:
  image: node:20
  cache: 
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: pull
  before_script:
    - date
    - npm install --progress=false
    - date
  after_script:
    - date

# Ce job devra être externalisé dans un fichier quand le bug sera fixé
# https://gitlab.com/remcohaszing/eslint-formatter-gitlab/-/issues/13
code:quality:
  stage: quality
  script:
    - npm run lint:ci
  allow_failure: true
  artifacts:
    reports:
      codequality: gl-codequality.json
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  timeout: 15m

include:
 - '.gitlab/ci/prepare.yml'
 - '.gitlab/ci/build.yml'
 - '.gitlab/ci/test.yml'
 - '.gitlab/ci/deploy.yml'
