# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - uses: actions/cache@v4.0.2
      with:
        path: ./node_modules
        key: dependencies_cache
    - run: npm run build --if-present

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - uses: actions/cache@v4.0.2
      with:
        path: ./node_modules
        key: dependencies_cache
    - run: npm ci
    - run: npm run test:unit:ci
