code:scan:
  stage: security
  image: returntocorp/semgrep
  needs: ['build:app']
  variables:
    SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN
    SEMGREP_RULES: p/default # See more rules at semgrep.dev/explore.
    SEMGREP_TIMEOUT: 300
    # Upload findings to GitLab SAST Dashboard
    SEMGREP_GITLAB_JSON: "1"
    GITLAB_TOKEN: $SEMGREP_APP_TOKEN
  before_script:
    - date
  script:
    - semgrep ci --gitlab-sast > gl-sast-report.json || true
  artifacts:
    reports:
      sast: gl-sast-report.json
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success

dependencies:scan:
  stage: security
  needs: ['build:app']
  cache: 
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: pull
  before_script:
    - date
    - npm install --progress=false --production
    - date
  script:
    - npm audit --audit-level=high --omit=dev
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  timeout: 5m